version: "3.7"

services:
  app:
    build: ../api
    ports:
      - 3000:3000
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: eth
      ME_CONFIG_MONGODB_URL: mongodb://root:eth@mongo/
  
  mongo:
    image: mongo
    restart: always
    ports: 
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: eth
